name: staging_deployment

on:
  push:
    tags:
      - v**-staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Building application
        run: |
          npm run build --
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Deploy to GCP Compute Engine
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.GCP_PRIVATE_KEY }}" > ~/.ssh/google_compute_engine
          chmod 400 ~/.ssh/gotem-keypair
          echo -e "${{ secrets.GCP_PUBLIC_KEY }}" > ~/.ssh/google_compute_engine.pub
          chmod 644 ~/.ssh/gotem-keypair.pub
          gcloud compute scp --recurse dist/browser/* ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }}:${{ secrets.GCP_PATH }} --zone=${{ secrets.GCP_ZONE }}
          gcloud compute ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} --zone=${{ secrets.GCP_ZONE }} --command="sudo systemctl restart nginx"