name: staging_deployment

on:
  push:
    tags:
      - v**-staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Building application
        run: |
          npm run build --
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Upload files to VM
        run: |
          mkdir ~/.ssh 
          echo "${{ secrets.GCP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa 
          gcloud compute scp --recurse dist/browser/* ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }}:${{ secrets.GCP_PATH }} --zone=${{ secrets.GCP_ZONE }}
      - name: Deploy application on VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} --zone=${{ secrets.GCP_ZONE }} --command="cd ${{ secrets.GCP_PATH }} && sudo systemctl restart nginx"
  